name: Create Archive
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: "release-${{GITHUB_REF/refs\/tags\//}}.zip"

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "release-${{GITHUB_REF/refs\/tags\//}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}